name = "sql_equiv"
version = "0.1.0"
defaultTargets = ["sql_equiv"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "main"

[[require]]
name = "LSpec"
git = "https://github.com/argumentcomputer/LSpec"
rev = "main"

[[lean_lib]]
name = "SqlEquiv"

[[lean_lib]]
name = "Test"
globs = ["Test.*"]

[[lean_exe]]
name = "sql_equiv"
root = "Main"

[[lean_exe]]
name = "sql_equiv_test"
root = "Test.Main"

[[lean_lib]]
name = "LSpecTests"
globs = ["LSpecTests.*"]

[[lean_exe]]
name = "sql_equiv_lspec"
root = "LSpecTests.Main"
